baseURL = "https://natalia-espinosadice.github.io/"
languageCode = "en-us"
title = "Natalia Espinosa Dice"
theme = "typo"
enableRobotsTXT = true

[params]
  description = "research interests"
  defaultTheme = "auto"   # light/dark auto
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3