baseURL = "https://natalia-espinosadice.github.io/"
languageCode = "en-us"
title = "Natalia Espinosa Dice"
theme = "typo"
enableRobotsTXT = true

[params]
  description = "research interests"
  defaultTheme = "auto"

  # Header menu for Typo:
  [[params.menu]]
    name = "/Projects"
    url  = "projects"

