baseURL = "https://natalia-espinosadice.github.io/"
languageCode = "en-us"
title = "Natalia Espinosa Dice"
theme = "typo"
enableRobotsTXT = true

[params]
    defaultTheme = "auto"
    [[params.menu]]
        name = "Home"
        url = "/"
        weight = 1
    [[params.menu]]
        name = "Publications"
        url  = "/publications"
    [[params.menu]]
        name = "Research"
        url  = "/research"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      unsafe = true

  