baseURL = "https://natalia-espinosadice.github.io/"
languageCode = "en-us"
title = "Natalia Espinosa Dice"
theme = "typo"
enableRobotsTXT = true

[params]
    defaultTheme = "auto"
    
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[params.menu]]
        name = "Projects"
        url  = "/projects"



