baseURL = "https://natalia-espinosadice.github.io/"
languageCode = "en-us"
title = "Natalia Espinosa Dice"
theme = "typo"
enableRobotsTXT = true

[params]
  description = "research interests"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2

